project: "RL Trading"
program: bayes_sweep.py
method: bayes
metric:
  name: avg_reward
  goal: maximize
parameters:
  lr_actor:
    min: 0.00001
    max: 0.001
    scale: log
  lr_critic:
    min: 0.00001
    max: 0.001
    scale: log
  action_std:
    min: 0.1
    max: 1.0
    scale: linear
  update_epochs:
    min: 1
    max: 10
    scale: linear
  clip_param:
    min: 0.1
    max: 0.3
    scale: linear
  entropy_beta:
    min: 0.0001
    max: 0.01
    scale: log